name       : xclip
version    : 0.12
release    : 1
source     :
    - http://freefr.dl.sourceforge.net/project/xclip/xclip/0.12/xclip-0.12.tar.gz : b7c7fad059ba446df5692d175c2a1d3816e542549661224806db369a0d716c45
license    : GPL-2.0
summary    : xclip is a command line interface to the X11 clipboard.
description: |
    xclip is a command line interface to the X11 clipboard.
builddeps  :
    - pkgconfig(xmu)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
