name       : xclip
version    : 0.13
release    : 2
source     :
    - https://github.com/astrand/xclip/archive/0.13.tar.gz : ca5b8804e3c910a66423a882d79bf3c9450b875ac8528791fb60ec9de667f758
license    : GPL-2.0
component  : xorg.apps
summary    : xclip is a command line interface to the X11 clipboard.
description: |
    xclip is a command line interface to the X11 clipboard.
builddeps  :
    - pkgconfig(xmu)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
